FROM ubuntu:20.04

LABEL description = "Imagen para desarrollar con web.py"
LABEL mainteiner = "Salvador HM"
LABEL version = "0.1"

RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip3 install flask